
dados = {
    'Origem': [rf'C:\Users\Igor\Desktop\notas\3sixty_produtora_de_eventos_e_live_mar_780841',
            rf'C:\Users\Igor\Desktop\notas\acp_matriz_794320',
            rf'C:\Users\Igor\Desktop\notas\ac_yabiku_filial_780767',
            rf'C:\Users\Igor\Desktop\notas\ac_yabiku_matriz_780751',
            rf'C:\Users\Igor\Desktop\notas\agile_com_varej_de_prod_eletromedicos_780810',
            rf'C:\Users\Igor\Desktop\notas\aguaplus_pocos_artesianos_-_eireli_794324',
            rf'C:\Users\Igor\Desktop\notas\barao_esquadrias_de_madeiras_ltda_780757',
            rf'C:\Users\Igor\Desktop\notas\bdm_micromercados_ltda_780823',
            rf'C:\Users\Igor\Desktop\notas\bimetal_matriz_794330',
            rf'C:\Users\Igor\Desktop\notas\blg_comercial_prod._naturais_e_cosm.ei_794332',
            rf'C:\Users\Igor\Desktop\notas\cinomatic_do_brasil_industria_e_comerc_780731',
            rf'C:\Users\Igor\Desktop\notas\clinica_veterinaria_nosso_lar_ltda_794339',
            rf'C:\Users\Igor\Desktop\notas\clisol_filial_909863',
            rf'C:\Users\Igor\Desktop\notas\clisol_matriz_909858',
            rf'C:\Users\Igor\Desktop\notas\cypriano_vieira_desiderato_794341',
            rf'C:\Users\Igor\Desktop\notas\deplasti_industria_e_comercio_de_plast_794344',
            rf'C:\Users\Igor\Desktop\notas\desiderato_sorvetes_finos_ltda_-_me_794345',
            rf'C:\Users\Igor\Desktop\notas\dixmedical_produtos_para_a_saude_ltda_837401',
            rf'C:\Users\Igor\Desktop\notas\elabore_repr_e_assist_tecnica_ltda_780846',
            rf'C:\Users\Igor\Desktop\notas\elias_liberato_artefatos_794347',
            rf'C:\Users\Igor\Desktop\notas\engpoint_servicos_de_engenharia_ltda_780819',
            rf'C:\Users\Igor\Desktop\notas\g4_brasil_ind.e_com._de_equip_elet.l_794350',
            rf'C:\Users\Igor\Desktop\notas\garagem_120_mecanica_e_publicidade_794351',
            rf'C:\Users\Igor\Desktop\notas\garage_637_inj._peas_e_serv._ltda_me_780738',
            rf'C:\Users\Igor\Desktop\notas\glk_eletronica_indst.com._ltda_epp_794352',
            rf'C:\Users\Igor\Desktop\notas\hmf_sistemas_de_energia_comercio_e_imp_780804',
            rf'C:\Users\Igor\Desktop\notas\i-solutioncard_comercio_e_servicos_ltd_794357',
            rf'C:\Users\Igor\Desktop\notas\italjato_comercio_de_pecas_ltda_780820',
            rf'C:\Users\Igor\Desktop\notas\itambras_importacao_e_exportacao_ltda_794358',
            rf'C:\Users\Igor\Desktop\notas\jose_mario_galli_desiderato_-_me_794359',
            rf'C:\Users\Igor\Desktop\notas\khromo_technology_do_brasil_sociedade_ltda_1331455',
            rf'C:\Users\Igor\Desktop\notas\ls_comercio_e_solucao_especializada_em_780814',
            rf'C:\Users\Igor\Desktop\notas\marco_27_ltda_epp_780730',
            rf'C:\Users\Igor\Desktop\notas\maxxikit_auto_parts_industria__comerc_794363',
            rf'C:\Users\Igor\Desktop\notas\med_pet_shop_ltda_me_794364',
            rf'C:\Users\Igor\Desktop\notas\mercadinho_e_padaria_wk_794366',
            rf'C:\Users\Igor\Desktop\notas\mt_wataya_nakao_me_794367',
            rf'C:\Users\Igor\Desktop\notas\new_tech_sistemas_de_energia_ltda_794368',
            rf'C:\Users\Igor\Desktop\notas\nlb_comercio_de_maquin.e_peas_eireli_780779',
            rf'C:\Users\Igor\Desktop\notas\nlb_industria_de_maquinas_e_equipament_780758',
            rf'C:\Users\Igor\Desktop\notas\obah_produtos_e_servicos_analiticos_lt_780748',
            rf'C:\Users\Igor\Desktop\notas\opticam_tecnologia_918439',
            rf'C:\Users\Igor\Desktop\notas\oswar_aparecido_momesso_henk_me_794370',
            rf'C:\Users\Igor\Desktop\notas\ouro_branco_transp._de_agua__ltda_794371',
            rf'C:\Users\Igor\Desktop\notas\r2c_eventos_ltda_780834',
            rf'C:\Users\Igor\Desktop\notas\r2_empreendimentos_1193371',
            rf'C:\Users\Igor\Desktop\notas\ry_sistema_m._e._e._e_persolizado_794375',
            rf'C:\Users\Igor\Desktop\notas\salgateria_e_pastelaria_da_divisa_ltda_780768',
            rf'C:\Users\Igor\Desktop\notas\sisnac_filial_sc_794403',
            rf'C:\Users\Igor\Desktop\notas\sisnac_matriz_780752',
            rf'C:\Users\Igor\Desktop\notas\swiss_revestimentos_ltda_-_epp_780795',
            rf'C:\Users\Igor\Desktop\notas\teknovation_equipamentos_e_servios_ltda_972056',
            rf'C:\Users\Igor\Desktop\notas\tempersol_engenharia_ltda._794388',
            rf'C:\Users\Igor\Desktop\notas\tes_design_locacao_e_instalacao_de_equ_780776',
            rf'C:\Users\Igor\Desktop\notas\tubolar_materiais_p_construc.ltda_me_794390',
            rf'C:\Users\Igor\Desktop\notas\tutti_belli_comercio_de_flores_ltda_me_794391',
            rf'C:\Users\Igor\Desktop\notas\twr_filial_am_794393',
            rf'C:\Users\Igor\Desktop\notas\twr_matriz_794392',
            rf'C:\Users\Igor\Desktop\notas\yabiku_filial_l3_780759',
            rf'C:\Users\Igor\Desktop\notas\yabiku_filial_l6_780787',
            rf'C:\Users\Igor\Desktop\notas\yabiku_filial_l7_794398',
            rf'C:\Users\Igor\Desktop\notas\yabiku_filial_l8_780832',
            rf'C:\Users\Igor\Desktop\notas\yabiku_matriz_780727',
            rf'C:\Users\Igor\Desktop\notas\yurika_comercio_de_massas_ltda_epp_780736',
            rf'C:\Users\Igor\Desktop\notas\zc_rubber_brazil_import_e_export_ltda_780769',
            rf'C:\Users\Igor\Desktop\notas\bimetal_filial_794331',
            rf'C:\Users\Igor\Desktop\notas\fernandes_lucena_empreendimentos_imobi_780747',
            rf'C:\Users\Igor\Desktop\notas\ga.v.a_projetos_e_solues_ltda_epp_780847',
            rf'C:\Users\Igor\Desktop\notas\project_corp_coml_e_serv_em_imoveis_780762',
            rf'C:\Users\Igor\Desktop\notas\r1_audiovisual_locao_de_equipamentos_780793',
            rf'C:\Users\Igor\Desktop\notas\r1_solutions_informatica_eireli_epp_780743',
            rf'C:\Users\Igor\Desktop\notas\str_comercio_de_vidros_ltda_-_epp_780761'],

    'Destino': [r'W:\Shared With Me\Clientes\3sixty Produtora\2024\Fiscal',
                r'W:\Shared With Me\Clientes\ACP\2024\Fiscal',
                r'W:\Shared With Me\Clientes\A&C Yabiku (filial 1) L4\2024\Fiscal',
                r'W:\Shared With Me\Clientes\A&C Matriz\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Agile\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Aguaplus Poços\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Iris & Gustavo\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Bdm\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Bimetal Engenharia (matriz)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Blg Comercial\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Cinomatic\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Clinica Valentim\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Clisol Products (filial)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Clisol Products (matriz)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Cypriano\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Deplasti\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Desiderato Sorvetes\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Dixmedical Produtos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Elabore Representaçoes\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Elias Liberato\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Engpoint Serviços\2024\Fiscal',
                r'W:\Shared With Me\Clientes\G4 Brasil\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Garagem 120\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Garage 637\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Glk Eletronica\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Hmf Sistemas de Energia\2024\Fiscal',
                r'W:\Shared With Me\Clientes\I Solutioncard\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Italjato\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Itambrás\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Jose Mario Galli\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Khromo Tech\2024\Fiscal',
                r'W:\Shared With Me\Clientes\LS Comercio (Lar Santa)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Marco 27\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Maxxikit\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Med Pet\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Mercadinho WK\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Mt Wataya\2024\Fiscal',
                r'W:\Shared With Me\Clientes\New Tech\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Nlb Comércio\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Nlb Indústria\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Obah Produtos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Opticam Tecnologia\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Oswar Aparecido\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Ouro Branco\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R2C Eventos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R2 Empreendimentos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R&Y Sistema\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Salgateria\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Sisnac filial\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Sisnac\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Swiss Revestimentos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Teknovation\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tempersol Engenharia\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tes Design\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tubolar Materiais\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tutti Belli\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Twr filial manaus (filial 02)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\TWR Matriz\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 01) L3\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 02) L6\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 03) L7\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 05) L8\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (matriz) L1\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yurika Comércio\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Zc Rubber\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Bimetal Filial\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Fernandes Lucena Matriz\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Gava Projetos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Project Corp\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R1 Audiovisual (letsee)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R1 Eventos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Str Comércio\2024\Fiscal']
}
