
dados = {
    'Origem': [
                rf'C:\Users\Igor\Desktop\notas\YABIKU MATRIZ',
                rf'C:\Users\Igor\Desktop\notas\MARCO 27 LTDA EPP',
                rf'C:\Users\Igor\Desktop\notas\CINOMATIC DO BRASIL INDUSTRIA E COMERC',
                rf'C:\Users\Igor\Desktop\notas\YURIKA COMERCIO DE MASSAS LTDA EPP',
                rf'C:\Users\Igor\Desktop\notas\OBAH PRODUTOS E SERVICOS ANALITICOS LT',
                rf'C:\Users\Igor\Desktop\notas\A&C YABIKU MATRIZ',
                rf'C:\Users\Igor\Desktop\notas\SISNAC MATRIZ',
                rf'C:\Users\Igor\Desktop\notas\BARAO ESQUADRIAS DE MADEIRAS LTDA',
                rf'C:\Users\Igor\Desktop\notas\NLB INDUSTRIA DE MAQUINAS E EQUIPAMENT',
                rf'C:\Users\Igor\Desktop\notas\YABIKU FILIAL L3',
                rf'C:\Users\Igor\Desktop\notas\A&C YABIKU FILIAL',
                rf'C:\Users\Igor\Desktop\notas\SALGATERIA E PASTELARIA DA DIVISA LTDA',
                rf'C:\Users\Igor\Desktop\notas\ZC RUBBER BRAZIL IMPORT E EXPORT LTDA',
                rf'C:\Users\Igor\Desktop\notas\TES DESIGN LOCACAO E INSTALACAO DE EQU',
                rf'C:\Users\Igor\Desktop\notas\NLB COMERCIO DE MAQUIN.E PEcAS EIRELI',
                rf'C:\Users\Igor\Desktop\notas\YABIKU FILIAL L6',
                rf'C:\Users\Igor\Desktop\notas\SWISS REVESTIMENTOS LTDA - EPP',
                rf'C:\Users\Igor\Desktop\notas\HMF SISTEMAS DE ENERGIA COMERCIO E IMP',
                rf'C:\Users\Igor\Desktop\notas\AGILE COM VAREJ DE PROD ELETROMEDICOS',
                rf'C:\Users\Igor\Desktop\notas\LS COMERCIO E SOLUCAO ESPECIALIZADA EM',
                rf'C:\Users\Igor\Desktop\notas\ENGPOINT SERVICOS DE ENGENHARIA LTDA',
                rf'C:\Users\Igor\Desktop\notas\ITALJATO COMERCIO DE PECAS LTDA',
                rf'C:\Users\Igor\Desktop\notas\BDM MICROMERCADOS LTDA',
                rf'C:\Users\Igor\Desktop\notas\YABIKU FILIAL L8',
                rf'C:\Users\Igor\Desktop\notas\R2C EVENTOS LTDA',
                rf'C:\Users\Igor\Desktop\notas\3SIXTY PRODUTORA DE EVENTOS E LIVE MAR',
                rf'C:\Users\Igor\Desktop\notas\ELABORE REPR E ASSIST TECNICA LTDA',
                rf'C:\Users\Igor\Desktop\notas\ACP MATRIZ',
                rf'C:\Users\Igor\Desktop\notas\AGUAPLUS POCOS ARTESIANOS - EIRELI',
                rf'C:\Users\Igor\Desktop\notas\BIMETAL MATRIZ',
                rf'C:\Users\Igor\Desktop\notas\BLG COMERCIAL PROD. NATURAIS E COSM.EI',
                rf'C:\Users\Igor\Desktop\notas\CLINICA VETERINARIA NOSSO LAR LTDA',
                rf'C:\Users\Igor\Desktop\notas\CYPRIANO VIEIRA DESIDERATO',
                rf'C:\Users\Igor\Desktop\notas\DEPLASTI INDUSTRIA E COMERCIO DE PLAST',
                rf'C:\Users\Igor\Desktop\notas\DESIDERATO SORVETES FINOS LTDA - ME',
                rf'C:\Users\Igor\Desktop\notas\ELIAS LIBERATO ARTEFATOS',
                rf'C:\Users\Igor\Desktop\notas\G4 BRASIL IND.E COM. DE EQUIP ELET.L',
                rf'C:\Users\Igor\Desktop\notas\GARAGEM 120 MECANICA E PUBLICIDADE',
                rf'C:\Users\Igor\Desktop\notas\GLK ELETRONICA INDUST.COM. LTDA EPP',
                rf'C:\Users\Igor\Desktop\notas\I-SOLUTIONCARD COMERCIO E SERVICOS LTD',
                rf'C:\Users\Igor\Desktop\notas\ITAMBRAS IMPORTACAO E EXPORTACAO LTDA',
                rf'C:\Users\Igor\Desktop\notas\JOSE MARIO GALLI DESIDERATO - ME',
                rf'C:\Users\Igor\Desktop\notas\MAXXIKIT AUTO PARTS INDUSTRIA & COMERC',
                rf'C:\Users\Igor\Desktop\notas\MED PET SHOP LTDA ME',
                rf'C:\Users\Igor\Desktop\notas\MERCADINHO E PADARIA WK',
                rf'C:\Users\Igor\Desktop\notas\MT WATAYA NAKAO ME',
                rf'C:\Users\Igor\Desktop\notas\NEW TECH SISTEMAS DE ENERGIA LTDA',
                rf'C:\Users\Igor\Desktop\notas\OSWAR APARECIDO MOMESSO HENK ME',
                rf'C:\Users\Igor\Desktop\notas\OURO BRANCO TRANSP. DE AGUA LTDA',
                rf'C:\Users\Igor\Desktop\notas\R&Y SISTEMA M. E. E. E PERSOLIZADO',
                rf'C:\Users\Igor\Desktop\notas\TEMPERSOL ENGENHARIA LTDA.',
                rf'C:\Users\Igor\Desktop\notas\TUBOLAR MATERIAIS',
                rf'C:\Users\Igor\Desktop\notas\TUTTI BELLI COMERCIO DE FLORES LTDA ME',
                rf'C:\Users\Igor\Desktop\notas\TWR MATRIZ',
                rf'C:\Users\Igor\Desktop\notas\TWR FILIAL AM',
                rf'C:\Users\Igor\Desktop\notas\YABIKU FILIAL L7',
                rf'C:\Users\Igor\Desktop\notas\SISNAC FILIAL SC',
                rf'C:\Users\Igor\Desktop\notas\DIXMEDICAL PRODUTOS PARA A SAUDE LTDA',
                rf'C:\Users\Igor\Desktop\notas\CLISOL MATRIZ',
                rf'C:\Users\Igor\Desktop\notas\CLISOL FILIAL',
                rf'C:\Users\Igor\Desktop\notas\OPTICAM TECNOLOGIA',
                rf'C:\Users\Igor\Desktop\notas\TEKNOVATION EQUIPAMENTOS E SERVIcOS LTDA',
                rf'C:\Users\Igor\Desktop\notas\R2 EMPREENDIMENTOS',
                rf'C:\Users\Igor\Desktop\notas\KHROMO TECHNOLOGY DO BRASIL SOCIEDADE LTDA'
            ],

    'Destino': [r'W:\Shared With Me\Clientes\Yabiku Materiais (matriz) L1\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Marco 27\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Cinomatic\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yurika Comércio\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Obah Produtos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\A&C Matriz\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Sisnac\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Iris & Gustavo\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Nlb Comércio\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 01) L3\2024\Fiscal',
                r'W:\Shared With Me\Clientes\A&C Yabiku (filial 1) L4\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Salgateria\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Zc Rubber\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tes Design\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Nlb Comércio\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 02) L6\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Swiss Revestimentos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Hmf Sistemas de Energia\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Agile\2024\Fiscal',
                r'W:\Shared With Me\Clientes\LS Comercio (Lar Santa)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Engpoint Serviços\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Italjato\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Bdm\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 05) L8\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R2C Eventos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\3sixty Produtora\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Elabore Representaçoes\2024\Fiscal',
                r'W:\Shared With Me\Clientes\ACP\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Aguaplus Poços\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Bimetal Engenharia (matriz)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Blg Comercial\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Clinica Valentim\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Cypriano\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Deplasti\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Desiderato Sorvetes\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Elias Liberato\2024\Fiscal',
                r'W:\Shared With Me\Clientes\G4 Brasil\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Garagem 120\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Glk Eletronica\2024\Fiscal',
                r'W:\Shared With Me\Clientes\I Solutioncard\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Itambrás\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Jose Mario Galli\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Maxxikit\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Med Pet\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Mercadinho WK\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Mt Wataya\2024\Fiscal',
                r'W:\Shared With Me\Clientes\New Tech\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Oswar Aparecido\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Ouro Branco\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R&Y Sistema\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tempersol Engenharia\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tubolar Materiais\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Tutti Belli\2024\Fiscal',
                r'W:\Shared With Me\Clientes\TWR Matriz\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Twr filial manaus (filial 02)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Yabiku Materiais (filial 03) L7\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Sisnac filial\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Dixmedical Produtos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Clisol Products (filial)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Clisol Products (filial)\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Opticam Tecnologia\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Teknovation\2024\Fiscal',
                r'W:\Shared With Me\Clientes\R2 Empreendimentos\2024\Fiscal',
                r'W:\Shared With Me\Clientes\Khromo Tech\2024\Fiscal'
    ]
}
